### ISSUE TITLE
getting FATAL: Invalid character 'L' looking for beginning of value exit status 2

### ISSUE THREAD

**Issue by l0master** [drbig/catatools#1]
Prepare command worked just fine, creating terrain.dat file. But after trying 
d:\Go\bin>go run overmapper-2.go convert d:\cat\cat\save\italy > d:\cat\test.html
i receive that error: FATAL: Invalid character 'L' looking for beginning of value exit status 2

**Comment by drbig** [comment]
Thanks for reporting! If you feel like it you might try running the Ruby version to see if it blows up too.

**Comment by l0master** [comment]
Some time later. I don't have Ruby environment yet. Also i'd like to mention that color styles are generated OK. So my 'test.html' is actually created but looks like this

<html><head><style>
body { background: black; color: #aaaaaa; }
.cl_white { color: #ffffff; }
.cl_blue { color: #0000ff; }
.cl_red { color: #ff0000; }
.cl_brown { color: #a52a2a; }
.cl_green { color: #008000; }
.cl_cyan { color: #00ffff; }
.cl_dark_gray { color: #a9a9a9; }
.cl_magenta { color: #ff00ff; }
.cl_yellow { color: #ffff00; }
.cl_light_blue { color: #add8e6; }
.cl_light_green { color: #90ee90; }
.cl_light_red { color: #ff5555; }
.cl_i_ltred { color: black; background: #ff5555; }
.cl_light_gray { color: #d3d3d3; }
.cl_i_ltgray { color: black; background: #d3d3d3; }
.cl_light_cyan { color: #e0ffff; }
.cl_ltgray_yellow { color: #d3d3d3; background: #ffff00; }
.cl_pink { color: #ffc0cb; }
.cl_yellow_magenta { color: #ffff00; background: #ff00ff; }
.cl_white_magenta { color: #ffffff; background: #ff00ff; }
.cl_i_magenta { color: black; background: #ff00ff; }
.cl_pink_magenta { color: #ffc0cb; background: #ff00ff;  }
.cl_i_green { color: black; background: #008000; }
.cl_i_brown { color: black; background: #a52a2a; }
.cl_h_yellow { color: #ffff00; background: #0000ff; }
.cl_h_dkgray { color: #a9a9a9; background: #0000ff; }
.cl_i_ltblue { color: black; background: #add8e6; }
.cl_i_blue { color: black; background: #0000ff; }
.cl_i_red { color: black; background: #ff0000; }
.cl_ltgreen_yellow { color: #d3d3d3; background: #ffff00; }
.cl_white_white { background: white; }
.cl_i_ltcyan { color: black; background: #e0ffff; }
.cl_yellow_cyan { color: #ffff00; background: #00ffff; }
</style><meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
</head><body><pre>

**Comment by bronekalmar** [comment]
I have the same error on overmapper-2.go
also on overmapper-2.rb i have this

./overmapper-2.rb:79: unknown type of %string
    FORMATS = %i{txt html}
./overmapper-2.rb:79: syntax error, unexpected $end
    FORMATS = %i{txt html}

GO version 1.5
Ruby version 2.2.1

**Comment by bronekalmar** [comment]
For example, I opened o.0.0 file,the first four lines are:

# version 23

L 0
rock 3528 slimepit 3 rock 177 slimepit 3 rock 175 slimepit 5 rock 1 slimepit 4 rock 170 slimepit 3 rock 3 slimepit 5 rock 169 slimepit 3 rock 3 slimepit 5 rock 175 slimepit 5 rock 172 slimepit 8 rock 172 slimepit 5 rock 175 slimepit 5 rock 175 slimepit 5 rock 171 slimepit 9 rock 172 slimepit 5 rock 174 slimepit 6 rock 4 slimepit 3 rock 168 slimepit 5 rock 4 slimepit 3 rock 167 slimepit 2 rock 1 slimepit 2 rock 5 slimepit 3 rock 4640 rift 3 rock 41 slimepit 3 rock 134 rift 2 rock 41 slimepit 3 rock 134 rift 3 rock 40 slimepit 3 rock 135 rift 3 rock 178 rift 3 rock 178 rift 3 rock 39 slimepit 3 rock 136 rift 2 rock 40 slimepit 4 rock 135 rift 2 rock 38 slimepit 5 rock 136 rift 2 rock 37 slimepit 5 rock 136 rift 3 rock 34 slimepit 6 rock 138 rift 3 rock 33 slimepit 4 rock 141 rift 2 rock 32 slimepit 6 rock 141 rift 2 rock 31 slimepit 6 rock 142 rift 2 rock 30 slimepit 6 rock 143 rift 2 rock 29 slimepit 6 rock 144 hellmouth 2 rock 28 slimepit 8 rock 143 rift 1 rock 28 slimepit 8 rock 143 rift 2 rock 27 slimepit 8 rock 12 slimepit 10 rock 122 rift 2 rock 27 slimepit 6 rock 13 slimepit 5 rock 1 slimepit 4 rock 123 rift 2 rock 26 slimepit 5 rock 14 slimepit 5 rock 1 slimepit 4 rock 124 rift 2 rock 27 slimepit 1 rock 1 slimepit 1 rock 15 slimepit 9 rock 125 rift 1 rock 44 slimepit 11 rock 125 rift 1 rock 43 slimepit 2 rock 1 slimepit 8 rock 126 rift 1 rock 41 slimepit 13 rock 125 rift 2 rock 41 slimepit 4 rock 1 slimepit 7 rock 126 rift 2 rock 39 slimepit 5 rock 1 slimepit 3 rock 131 rift 1 rock 39 slimepit 5 rock 1 slimepit 3 rock 132 rift 1 rock 39 slimepit 2 rock 1 slimepit 1 rock 137 rift 1 rock 180 rift 1 rock 10795 slimepit 1 rock 1 slimepit 2 rock 176 slimepit 5 rock 176 slimepit 4 rock 175 slimepit 5 rock 176 slimepit 4 rock 4936
L 1

first line begins with # and seems no problem with it
each remaining line begins with "L" and "rock" in turn
then I removed first two lines, so first symbol is "r" now

this time error is 
FATAL:  invalid character 's' looking for beginning of value
exit status 2

sorry for my english :)

**Comment by drbig** [comment]
> version 23

There's your problem :) The overmapper works only with saves from recent (past 0.C stable) C:DDA versions (to be specific: **Works only with saves since JSON overmap saving became a thing.** Perhaps read more carefully next time? :D)

**Comment by drbig** [comment]
Tested both the `overmapper-2.rb` and `overmapper.go` on fresh save from `0.C-8216-g5cbca0b` and it works as advertised.

**Comment by bronekalmar** [comment]
Thank you, that works)
